In [48]:
!pip install numpy

In [49]:
import numpy as np

# 1-D array in np

In [50]:
arr_1 = np.array([1,2,3,4])
print(arr_1)

[1 2 3 4]


# 2_D array

In [51]:
arr_2 = np.array([[1,2,3,4],[2,4,56,7],[6,7,9,5]])
print(arr_2)

[[ 1  2  3  4]
 [ 2  4 56  7]
 [ 6  7  9  5]]


# 3_D array
# Matrix

In [52]:
matrix = np.array([[1,2,3,4],[2,4,56,7]])
print(matrix)

[[ 1  2  3  4]
 [ 2  4 56  7]]


# Creating arrays from python lists

In [53]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


**using default values**

In [54]:
#only zeros
zeros_array = np.zeros(4)
print(zeros_array)

[0. 0. 0. 0.]


In [55]:
#for ones
ones_arr = np.ones((2,5),int)
print(ones_arr)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [56]:
# for specific number
full_arr = np.full((2,5),6)
print(full_arr)

[[6 6 6 6 6]
 [6 6 6 6 6]]


# creating sequences of numbers in numpy

In [57]:
#arrange(start,stop,step)
arr = np.arange(1,90,5)
print(arr)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86]


**Creating identity matrices**

In [58]:
identity_matrices = np.eye(4)
print( identity_matrices)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Properties of array

## **Checking**

**Shape**

In [59]:
arr = np.array([[1,2,3],[6,8,9]])
print(arr.shape)

(2, 3)


**Size**

In [60]:
arr = np.array([[1,2,3],[6,8,9]])
print(arr.size)

6


**ndim**

In [61]:
arr1d = np.array([1,2,3])
print(arr1d.ndim)
arr2d = np.array([[1,2,3],[6,8,9],[6,8,9],[7,8,9]])
print(arr2d.ndim)
arr3d = np.array([[[1,2,3],[6,8,9],[6,8,9],[7,8,9]]])
print(arr3d.ndim)

1
2
3


**Dtype(data type)**

In [62]:
arr = np.array([1,2.3,55])
print(arr.dtype)

float64


### Changing data type to another datatype

In [63]:
arr = np.array([1.3,4.5,56.7])
print(arr.dtype)
int_arr = arr.astype(int)
print(int_arr)
print(int_arr.dtype)

float64
[ 1  4 56]
int64


Maths in array

In [64]:
arr = np.array([1.3,4.5,56.7])
print(arr+5)
print(arr*5)
print(arr**5)

[ 6.3  9.5 61.7]
[  6.5  22.5 283.5]
[3.71293000e+00 1.84528125e+03 5.86023854e+08]


### **Aggregation function**

In [65]:
arr = np.array([1,2,4,6,78,90,24])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

205
29.285714285714285
1
90
35.483252732659615
1259.061224489796


# **Indexing / Slicing Arrays**

accessing index

In [66]:
# 1_D array
arr = np.array([2,3,9,40,56,70])
print(arr[3])
print(arr[-2])

40
56


In [67]:
# array have same length otherwise generate error
arr = np.array([[2,3,9,40,56,70], [23,45,7,12,56,7]])
print(arr[0,2])


9


Slicing

In [68]:
# array[start:stop:step]

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])
print(arr[:5])
print(arr[::3])
print(arr[::-1])#reverse an array without using loop

[2 3 4 5]
[1 2 3 4 5]
[ 1  4  7 10]
[10  9  8  7  6  5  4  3  2  1]


## **Fancy indexing**

In [69]:
# selecting multiple elements at ones
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[[0,2,6]])

[1 3 7]


Boolean *masking*

In [70]:
# filtering data base on conditions
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[arr >6])
#used in ML for filtering dataset important concept

[ 7  8  9 10]


# **Reshapeing & manipulating arrays**

reshape(rows,columns) specify new shape if dimensions match

changing the dimension shape with out modifying

In [71]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)
# reshaping does not create copy it returns a view which means it affect the array

[[1 2 3]
 [4 5 6]]


## **Flatting array**

when you want to covert multi dimensional array into 1d array

In [72]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ravel())
print(arr.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


# **Advanced Numpy**

array has fixed size

In [73]:
# insert(array,index,value,axis=None/0 for row/1 for column)
arr = np.array([1,2,3,4,5,6])
new_arr = np.insert(arr,3,20)
print(new_arr)

[ 1  2  3 20  4  5  6]


In [74]:
#insert in 2d
arr_2d = np.array([[1,2,3],[4,5,6]])
new_Arr = np.insert(arr_2d,1,[7,8,9],axis=0)
print(new_Arr)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


**Append**

In [75]:
arr = np.array([10,20,30])
new_arr = np.append(arr,[40,50,60])
print(new_arr)

[10 20 30 40 50 60]


**Concate**

In [76]:
# np.concatenate((array1,array2), axis = 0)

arr1 = np.array([1,2,3])
arr2 = np.array([11,22,33])
new_arr = np.concat((arr1,arr2), axis = 0)
print(new_arr)

[ 1  2  3 11 22 33]


**Removing element of array**

In [77]:
# new_arr = np.delete(array,index, axis= None)
arr = np.array([1,2,3])
new_arr = np.delete(arr,2, axis= None)
print(new_arr)

[1 2]


In [78]:
# new_arr = np.delete(arr_2d,row,colun, axis= 0)

arr_2d = np.array([[1,2,3],[4,5,6]])
new_arr = np.delete(arr_2d,0, axis= 0)
print(new_arr)


[[4 5 6]]


# **Stacking**

vertically
horizontally

vstack() row wise,
hstack() column wise

In [79]:
arr1 = np.array([1,2,3])
arr2 = np.array([11,22,33])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[ 1  2  3]
 [11 22 33]]
[ 1  2  3 11 22 33]


# **Splitting**
split() => equal,
hsplit() => hori,
vsplit() => verti


In [80]:
arr1 = np.array([1,2,3,4,5,6])
print(np.split(arr1,2))

[array([1, 2, 3]), array([4, 5, 6])]


# Broadcasting & Vectorization
perform operations on different shapes of array without using loops


because on small data loop works but on large data loop don't works


In [81]:
arr = np.array([100,200,300,400])
discount = 10
final_Array = arr - (arr*discount/100)
print(final_Array)

[ 90. 180. 270. 360.]


In [82]:
arr = np.array([100,200,300,400])
result = arr * 2
print(result)

[200 400 600 800]


### Matching dimensions

In [83]:
# 1D to 2D array

matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])
result = matrix + vector
print(result)

[[11 22 33]
 [14 25 36]]


### Incompatible shapes

In [84]:
# arr1 = np.array([[1,2,3],[4,5,6]])
# arr2 = np.array([10,20])
# result = arr1 + arr2
# print(result)

print("Solution of this problem is reshaping")
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([10,20])
arr5 = arr4.reshape(2,1)
result2 = arr5 + arr3
print(result2)

Solution of this problem is reshaping
[[11 12 13]
 [24 25 26]]


Vectorization

In [85]:
# slow
list1 = [1,2,3]
list2 = [3,4,5]
result = [x+y for x,y in zip(list1,list2)]
print(result)

[4, 6, 8]


In [86]:
#fast
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
result = arr1+arr2
print(result)

[4 6 8]


In [87]:
list1 = [1,2,3]
list2 = [3,4,5]
result = [x*y for x,y in zip(list1,list2)]
print(result)

[3, 8, 15]


In [88]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
result = arr1*arr2
print(result)

[ 3  8 15]


# Broadcasting


1.   Expend (Smaller to Larger)
2.   Faster Then Loops
3.   1D -> 2D
4.   Apply single value to an entire element

# Vectorization


1.   Apply Operation on Entire Array
2.   100x Faster then Loops
3.   Matrix operation





# Handdling Missing Values

isnan(array)

nan-to-num(array, nan=value,) default - 0

isinf(array)

In [89]:
arr = np.array([1,2,3,np.nan,5,np.nan])
print(np.isnan(arr))

[False False False  True False  True]


In [90]:
arr = np.array([1,2,3,np.nan,5,np.nan])
clear = np.nan_to_num(arr, nan = 100)
print(np.isnan(clear))

[False False False False False False]


In [91]:
arr = np.array([1,2,3,np.inf,5,np.inf])
print(np.isinf(arr))

[False False False  True False  True]


In [92]:
#replace a value
arr = np.array([1,2,3,np.inf,5,np.inf])

print(np.isinf(arr))
clear = np.nan_to_num(arr, posinf=100)
print(clear)

[False False False  True False  True]
[  1.   2.   3. 100.   5. 100.]
